name: test-update-config
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v3
      - run: echo "build"
      - uses: runs-on/cache/restore@3c223729b4fda74ee12f4976048dd69b420fdd26 # v5
